language: node_js
node_js:
- '8'
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
cache:
  yarn: true

script:
  - yarn build_binaries_for_distribution

deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_TOKEN"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
env:
  matrix:
    secure: nb8laYnasZp+ZMF0M/i1xnB3sTt7JBG5uXiPnlXJ2VYaTYP2QAO7ZQjgv9+Pw9Ry/IdUno4mSN7fTU7YuFWEv2ewYftLaE36lCo+0QL6vJmJ8HkDrENWCp3NOzSVKM4AwRgQKK1xej/6ZdE8QSRadFb3tIVnmvmD2+ngxdzKzKOufljLtjJXNNno9gGQi1h5Iay8cF3ZlDDt5emqC+nRkfDqfzPcfdGH2hijKuziOvWv0h7lpEJQiTEDzHvT08WcKOhfV61sP0d0S/8a0rlWmW1SbN4AXZtD6ezl3c7a+QhUxwCndhyazVvfbiQ7uwW69WjLMUiOj8CXk97wanJRpTLTyOzn07XGMLewfUHjFrvm+LcaJ4YrkbTqDOe4FZGQL9FNwQqdGoOzk9wv3A8lL9gg2dZrRoq/RyzbIoh1atOOR0buwU5SUcYhgh/x2KZ/GsUSQN30UQ8g0sLbYynNgn6yhHGfBzOsU+d6TQ4qjTyKtzoAC2UJgG5cfKPNuDiVlcPzKZJRXII4k8d7keFf9aLJBRspjBTDNah9scxUBvwQ1Nw1u5fa2ArAY6+laIgPrBeUJ5384SqWenO2XWx9e/sZS2vQcurjVL+zcM0iXt16nSKr5UHsxHp65BheHD+hs5+W4kjtIP/JFYy3jzOx+No4nnIeJxIu6VKtOa0Lo0w=
