language: node_js
node_js:
  - '8'

os:
  - linux
    dist: xenial
    sudo: required
  - osx
    osx_image: xcode8
cache:
  yarn: true
notifications:
  email: false

script:
  - yarn dist
deploy:
  provider: releases
  api_key: $ENCRYPTED_GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true

env:
  global:
    ENCRYPTED_GITHUB_TOKEN: S2nA2Kx0FeT5rmePZFqWGlL7UkUwlhg9lvo3BGYPz83KBYXseczt0u+pYbcfpyB1qdKLjirlxIoRdFzZY3v508R0kr5bFsfkBmpRq27m4Tbgxe23HBJv94vujrVsAWmdEQDsjqWdpBSa8WPqM+yFZGcIE82n/Hlh5yruExdwnPB4o7SZeLQN1T5hUeUe/XVTFT9hnh54/E7gEmG/8sDMMWlopN8CEt2b7fg491BSIjHHW6k+evrQOm4h5+wXYqWg93XiV4//Z85MdV+GPHR2/YeXkEcwTkprhosJHmZko92CNsHY20ilzlS6xN7efsOfaTJp9Is2joeee7OdtSEEy2Vo75RqsiA1xvjggarUjoqh2T8u26Ed0M58b53nt+wBFpyav1JWr0oiAsSUhc2AWh85mRsKDr/f0D/0CnqSNTPwbK6E4lZx1aFPtTfiTjbWbMmDsXc4MqXRYWYf7Q2hdD4/C3q98Kctfm/vBvjtZpo0EU2q+Z6ebv0SvssChowK9WXSf8BaBAIzH5+nlyNy6kci5HQj88gYmohe8mN3A+ighxvv/AXXBIfDatGAfajVMBba8h0Ia8uCwnXabYZg7Hjmeg4DCOCCbH0UXCDv713aq4MuBaaD0tpoQHSNaC9nZM75XI91qrlgAclpi0uJyYiLLCvzsSgi9/bA7328ats=
