language: node_js
node_js:
- '8'
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: osx

cache:
  yarn: true

before_install:
  - sudo apt-get install --assume-yes libgconf-2-4
script:
  - yarn test
  - NODE_ENV=production
  - yarn dist
notifications:
  email: false
env:
  matrix:
    # encrypted github token, stored as GH_TOKEN
    secure: QO+E0lIpeaHPidgvCVePG1h1NyMnlfK/9Vyo7rs1/EV5dAnvPOsqaYuA1ATsg15hDjhr4i8z4rFR6mm3wk7XPHP1lPz1Rve19brIvMvHU/riuxXHcYTUUhNUVL5B7sTE9oqSJfnvPIs/m2xHo9OFNR8v/IF5A7tsc1pO+clLWhTp9O+vtGbzisJPmoJVzQri/UjKIMJQttsytFz+DgOoQsRh7gOuQ5vWwJ35feiTLj4gTp0lR9U9BBgLVKL9gBlXfH60i0OeTouZ14bqlQSU/lJYn7OwzZecXYcFNw492wDc82rGyJi4deOnYqtq9w28wh8Ovj+lukJLWVS0oCME2WjPcYzuwj0f5Cw6Nqi/rFdQ927oQ9ftHmtEdk4drvfc1eoK1W1IutVTFgChVOkAjQ+ajKVhdQZF88lCiGKzgXqLL9PapCo9jkHp0II/gPBXpb5AuH1EtR7dDrrEysRe7et4OEyaGKqzsFKV+eVPMcZbwufcNOQ1inGkxXti1NR/WRIbB+bgNS4Fh2IYP+KDCQFW6UeQMFnH+dfBVTtp0o2aqPDe15H7jyvmmM7D5/qxKjsrE37bOxRL9s+jLG8Sm3t7VCc1AYkYOTZgdoIdfG+d3FadSUI7XZTNkpAiIDCPoq4thhLKp2HCQq7MOi3h6oWddAZEBBq0nXJGW3sM7Ps=
