version: 2 # CircleCI version 2

jobs:
    build:
        working_directory: ~/transcriptase
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: yarn install
            - run:
                name: Test
                command: yarn test
            - run:
                name: Build and Deploy
                command: yarn build_and_publish

