export const heresTheTranscript = "heres-the-transcript"
export const thereAreUnsavedChanges = "editor-is-dirty"
export const closeTheWindow = "close-the-window"

export const userHasChosenMediaFile = "user-has-chosen-a-media-file"
export const userHasChosenTranscriptFile = "user-has-chosen-a-transcript-file"
export const userSelectedMedia = "load-media-file"
export const userWantsToLoadMedia = "user-wants-to-load-media"
export const userWantsToSaveTranscript = "user-wants-to-save-transcript"
export const userHasToggledPlayPause = "user-has-toggled-play-pause"
export const jumpBackInTime = "jump-back-in-time"
export const readyToQuit = "app-is-safe-to-quit"
